ALTER TABLE site_visits
    ADD COLUMN funnel_stage VARCHAR(40),
    ADD COLUMN grade VARCHAR(80),
    ADD COLUMN goal VARCHAR(500),
    ADD COLUMN priority VARCHAR(500),
    ADD COLUMN updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;
